# Generated by Django 2.2 on 2020-10-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='carousel')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255)),
                ('desc', models.TextField(default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('photo1', models.ImageField(default='', upload_to='thumbnail')),
                ('photo2', models.ImageField(default='', upload_to='thumbnail')),
                ('photo3', models.ImageField(default='', upload_to='thumbnail')),
                ('day', models.CharField(default='', max_length=100)),
                ('Price', models.CharField(default='', max_length=100)),
                ('seat', models.CharField(default='', max_length=20)),
                ('meeting', models.CharField(default='', max_length=256)),
                ('discount', models.BooleanField(default=False)),
                ('discount_price', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking_app.Post')),
            ],
        ),
    ]
