# Generated by Django 2.2 on 2020-10-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='thumbnail'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='thumbnail'),
        ),
    ]
