# Generated by Django 2.2 on 2020-10-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_auto_20201018_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='discount',
            new_name='special',
        ),
        migrations.RemoveField(
            model_name='post',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='post',
            name='special_desc',
            field=models.TextField(default=''),
        ),
    ]
