# Generated by Django 2.2 on 2020-10-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_auto_20201019_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='special_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
