# Generated by Django 2.2 on 2020-10-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_auto_20201019_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='special_desc',
            field=models.TextField(blank=True, default='', max_length=620, null=True),
        ),
    ]
