# Generated by Django 2.2 on 2020-10-22 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_auto_20201019_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('cus_id', models.IntegerField(default='', max_length=25)),
                ('born', models.CharField(default='', max_length=20)),
                ('day', models.DateField(blank=True, default=datetime.date(2020, 10, 18), help_text='Today Date.', null=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone1', models.IntegerField(default='', max_length=15)),
                ('phone2', models.IntegerField(default='', max_length=15)),
                ('comment', models.TextField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Scheduling',
                'verbose_name_plural': 'Scheduling',
            },
        ),
    ]
