# Generated by Django 2.2 on 2020-10-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cus_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone1',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone2',
            field=models.IntegerField(default=''),
        ),
    ]
