# Generated by Django 2.2 on 2020-10-22 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_auto_20201022_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Scheduling', 'verbose_name_plural': 'Scheduling'},
        ),
        migrations.AddField(
            model_name='post',
            name='day1',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 18), help_text='Today Date.', null=True),
        ),
    ]
